version: "3.8"
services:
  server:
    build: .
    environment:
      ENV: development 
    volumes:
      # - ./data:/code/data
      - ./:/code
    restart: unless-stopped
    entrypoint: ["npm", "run", "dev"]
    ports: 
      - 5000:8080