version: "3.8"
services:
  db:
    image: mongo:4.4.2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 27hd!@Kslik
    ports:
      - 27017:27017
  server:
    build: .
    environment:
      ENV: production
    volumes:
      - ./data:/code/data
    restart: unless-stopped
    ports: 
      - 5000:8080
    depends_on:
      - db
    links:
      - db